// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ARow: typeof import('ant-design-vue/es')['Row']
    Datasaurus: typeof import('./src/components/Datasaurus.vue')['default']
    NetflixDistBar: typeof import('./src/components/NetflixDistBar.vue')['default']
    PreProcess: typeof import('./src/components/PreProcess.vue')['default']
    SVGdefs: typeof import('./src/components/SVGdefs.vue')['default']
  }
}

export {}
